[tool.poetry]
name = "ptz-controller"
version = "0.1.0"
description = ""
authors = ["Vitalii <tomchyshakvitalik@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pyserial = "^3.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
